### ISSUE TITLE
--bidir option bidirectional udp fails with "iperf3: error - unable to read from stream socket: Resource temporarily unavailable" on Windows

### ISSUE THREAD

**Issue by mochazi** [esnet/iperf#1354]
# Context

* Version of iperf3: iperf 3.11 (cJSON 1.7.13)

* Hardware: 
  Intel(R) Xeon(R) CPU E5-2680 (server) 
  Intel Celeron Dual-Core (client)
  
* Operating system (and distribution, if any):
  Ubuntu22.04 x64(client)
  Windows 10 21H2 x64(server)

_Please note: iperf3 is supported on Linux, FreeBSD, and macOS.
Support may be provided on a best-effort basis to other UNIX-like
platforms.  We cannot provide support for building and/or running
iperf3 on Windows, iOS, or Android._

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

I know iperf3 doesn't support windows, but I want to know why bidirectional udp fails?

# Bug Report

* Expected Behavior

I hope to add the --bidir option, it can also be tested normally like the default option

![image](https://user-images.githubusercontent.com/54659396/173979087-dc10b43c-17d0-4a2c-ae91-111113155fb9.png)

* Actual Behavior

After adding the --bidir option, it displays "socket: Resource temporarily unavailable"

![image](https://user-images.githubusercontent.com/54659396/173979431-e2b28c05-7df1-492a-9bc5-e5076899bdc1.png)

* Steps to Reproduce

Build iperf3 on Windows.
Use the `iperf3 -c <remotehost> -u --bidir` command on the client to connect to the server

![image](https://user-images.githubusercontent.com/54659396/173980841-2e6d1080-03b7-4375-8be0-e286b56ef3c9.png)

But, use Windows client to connect to Linux server, very stable.

![image](https://user-images.githubusercontent.com/54659396/173982076-8347e957-b7b1-4007-b105-56312b16113b.png)

Windows successfully connects to Linux, but Linux fails to connect to Windows. In theory, isn’t it interoperable?

Can someone tell me what is the reason for this?

**Comment by davidBar-On** [comment]
This is probably the same Cygwin issue with parallel UDP streams fixed by PR #1163 which is not (yet?) part of iperf3 mainline.

Can you test the code branch from the PR and see if it solves the problem?  Note the addition to the `-p` option that you will have to specify when running the server on Windows.

**Comment by mochazi** [comment]
> This is probably the same Cygwin issue with parallel UDP streams fixed by PR #1163 which is not (yet?) part of iperf3 mainline.
> 
> Can you test the code branch from the PR and see if it solves the problem? Note the addition to the `-p` option that you will have to specify when running the server on Windows.

Windows connects to Ubuntu normally.

![image](https://user-images.githubusercontent.com/54659396/174206191-d1b3762c-4552-45a5-af84-33b21ac3647f.png)

With the `-p` option added, the problem of ubuntu connecting to windows is still there.

![image](https://user-images.githubusercontent.com/54659396/174206720-3589e303-d819-40aa-8d25-b38de5f13f74.png)

I have pulled this fix branch and the compilation has passed, but I can still reproduce the problem.

**Comment by davidBar-On** [comment]
Seems I had to explain better the changes for `-p` in PR #1163.  On the Windows side (the server in this case), the `-p` also specifies the **number of ports available to be used**, starting from the port number specified by the parameter.

E.g. `--bidir` requires two ports, so `-p 5000/2` should be set and the server will use ports 5000 and 5001 for the two UDP stream (port 5000 is just an example taken from your test). `-P` is similar - e.g. `-p 5000/4` should be used for `-P 4` (using ports 5000-50003).

Note that since it may not be known ahead how may ports will be required by the clients, the number of ports set should be the number of expected maximum streams.  E.g. if it is expected that up to 20 streams may be used by the clients (`-P 20`), `-p 5000/20` should be set for the server (and ports 5000-5019) should be available for the server).

Can you retry with setting the number of ports available?

**Comment by mochazi** [comment]
Sorry, I forgot to reply when I saw the email earlier. Now go ahead and test `--bidir`. I used `-p 5000/2` and it still doesn't work.

![image](https://user-images.githubusercontent.com/54659396/178396203-002e09d4-c246-4f5b-9df5-0420056ead1a.png)

**Comment by davidBar-On** [comment]
@mochazi, did you compile and used for the server the iperf3 from  PR #1163?  I am asking, sine this PR code is based on version 3.10.1 and you are using version 3.11.  Note that the PR code is needed for the test, since it was not merged into iperf3 mainline (yet?).  You need this version only for the server side.

PR #1163 code branch that should be built for the test (Windows server) is: https://github.com/davidBar-On/iperf/tree/issues-472-1161-cygwin-parallel-udp-stearms

**Comment by Shapeno** [comment]
This bug is still exist what ever client OS is when windows as server even has administrator privileges. **Those UDP scenes are not work**:

```sh
iperf3 -c 1.1.10.1 -u --bidir
Connecting to host 1.1.10.1, port 5201
[  5] local 192.168.0.101 port 43785 connected to 1.1.10.1 port 5201
iperf3: error - unable to read from stream socket: Resource temporarily unavailable
```

```sh
iperf3 -c 1.1.10.1 -u -P 2
Connecting to host 1.1.10.1, port 5201
[  5] local 192.168.0.101 port 43322 connected to 1.1.10.1 port 5201
iperf3: error - unable to read from stream socket: Resource temporarily unavailable
```

these scenes works well in TCP porotocal.
These scenes are of great significance to us, can you fix them?

**Comment by davidBar-On** [comment]
Since PR #1163 was **not merged** (yet?) to iperf3 mainline, to fix the problem **the server should be built using PR #1163 code**.  I have now re-based the PR code to the latest iperf3 code (3.20+).
